dateModified: 1633919597
email:
  fromEmail: brettcrowley77@gmail.com
  fromName: 'Learn Nitro'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    5e0a5340-259b-4e7c-890e-e713c12d23cf: Common # Common
    6282dce0-af90-4339-8f35-4373cc4920d3: 'Learn Nitro' # Learn Nitro
    ae8796e9-c31c-44b5-abdc-9849d5aaad7c: 'Learn Nitro' # Learn Nitro
system:
  edition: solo
  live: true
  name: 'Learn Nitro'
  schemaVersion: 3.7.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
